language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install --upgrade pytest pytest-cov codecov
  - pip install .

script:
  - cd multinet && pytest --cov=multinet

after_success:
  - codecov
