language: python

matrix:
  include:
    - os: linux
      python: 2.7
      env:
      - REPORT_COVERAGE=1
    - python: 2.7
    - python: 3.6

before_install:
  - uname -a
  - printenv

install:
  - source tools/travis/linux_install.sh

script:
  - source tools/travis/script.sh

after_success:
  - if [[ "${REPORT_COVERAGE}" == 1 ]]; then
    codecov;
    fi

notification:
  email:false